public class Main {
    public static void main(String[] args) {
        System.out.println("Задание 1");
        int cat = 1000;
        System.out.println("Значение переменной cat типа int равно " + cat);
        byte dog = 100;
        System.out.println("Значение переменной dog типа byte равно " + dog);
        short hourse = 10000;
        System.out.println("Значение переменной houhse типа short равно " + hourse);
        long car = 1000000000L;
        System.out.println("Значение переменной car типа long равно " + car);
        float mouse = 10.50f;
        System.out.println("Значение переменной mouse типа float равно " + mouse);
        double mouseTwo = 10.33333333d;
        System.out.println("Значение переменной mouseTwo типа double равно " + mouseTwo);
        System.out.println("Задание 2");
        float a = 27.12f;
        long b = 987678965549L;
        float c = 2.786f;
        int d = 569;
        int e = -159;
        short f = 27897;
        byte g = 67;
        System.out.println("Задание 3");
        byte studentLudmila = 23;
        byte studentAnna = 27;
        byte studentEkaterina = 30;
        byte allStudens = (byte) (studentAnna + studentEkaterina + studentLudmila);
        int paper = 480;
        int forEveryStunent = paper / allStudens;
        System.out.println("На каждого ученика рассчитано " + forEveryStunent + " листов бумаги");
        System.out.println("Задание 4");
        byte productivityTwoMinutes = 16;
        byte productivityOneMinutes = (byte) (productivityTwoMinutes / 2);
        int productivityTwentyMinutes = (int) (productivityOneMinutes * 20);
        System.out.println("За 20 минут машина произвела " + productivityTwentyMinutes + " штук бутылок");
        int productivityDay = productivityOneMinutes * 1440;
        System.out.println("За сутки машина призвела " + productivityDay + " штук бутылок");
        int threeDays = productivityDay * 3;
        System.out.println("За трое суток машина произвела " + threeDays + " штук бутылок");
        int productivityMount = (short) (productivityDay * 31);
        System.out.println("За месяц машина произвела " + productivityMount + " штук бутылок");
        System.out.println("Задание 5");
        byte allCans = 120;
        byte allRooms = (byte) (allCans / 6);
        byte whiteCans = 20 * 2;
        byte brownCans = 20 * 4;
        System.out.println("В школе, где 20 классов, нужно " + whiteCans + " банок белой краски и " + brownCans + " банок коричневой краски");
        System.out.println("Задание 6");
        int banana = 80 * 5;
        int milk = 105 * 2;
        int iceCream = 100 * 2;
        int egg = 70 * 5;
        float allWeightGramm = banana + milk + iceCream + egg;
        float allWeightKilo = allWeightGramm / 1000;
        System.out.println("Масса одного завтрака - " + allWeightGramm + " граммов или " + allWeightKilo + " килограммов");
        System.out.println("Задание 7");
        float firstWeight = 0.250F;
        float secondWeight = 0.5F;
        float middleWeight = (firstWeight * secondWeight) / 2;
        byte needWeight = 7;
        float daysA = firstWeight * needWeight;
        float daysB = secondWeight * needWeight;
        float daysC = (daysA + daysB) / 2;
        System.out.println("Если спортсмен будет терять в день по 250 грамм, то ему понадобится " + daysA + " дней");
        System.out.println("Если спортсмен будет терять в день по 500 грамм, то ему понадобится " + daysB + " дней");
        System.out.println("В среднем спортсмену понадобится " + daysC + " дней");
        System.out.println("Задание 8");
        int masha = 67760;
        int denis = 83690;
        int kristina = 76230;
        float mashaM = (float) (masha * 1.1);
        float denisM = (float) (denis * 1.1);
        float kristinaM = (float) (kristina * 1.1);
        float mashaYear = masha * 12;
        float denisYear = denis * 12;
        float kristinaYear = kristina * 12;
        float mashaYearA = (float) (mashaYear * 1.1);
        float denisYearA = (float) (denisYear * 1.1);
        float kristinaYearA = (float) (kristinaYear * 1.1);
        int mashaA = (int) (mashaYearA - mashaYear);
        int denisA = (int) (denisYearA - denisYear);
        int kristinaA = (int) (kristinaYearA - kristinaYear);
        System.out.println("Маша теперь получает " + mashaM + " рублей. " + "Годовой доход вырос на " + mashaA + " рублей");
        System.out.println("Денис теперь получает " + denisM + " рублей. " + "Годовой доход вырос на " + denisA + " рублей");
        System.out.println("Кристина теперь получает " + kristinaM + " рублей. " + "Годовой доход вырос на " + kristinaA + " рублей");
    }
}